name: 'Begin Testbox'
description: 'Initialize a Blacksmith Testbox session. Phones home to receive config, installs SSH key and rsync.'

inputs:
  testbox_id:
    description: 'Testbox session ID (from workflow_dispatch input). Leave empty for validation mode.'
    required: false
    default: ''
  api_url:
    description: 'Override the backend API URL (default: discovered from VM metadata)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Check mode
      shell: bash
      run: |
        if [ -z "${{ inputs.testbox_id }}" ]; then
          echo "::notice::Running in validation mode — setup steps will be validated without starting a testbox session."
        fi

    - name: Discover metadata service
      id: metadata
      shell: bash
      run: |
        METADATA_PORT="${METADATA_PORT:-}"
        if [ -z "$METADATA_PORT" ]; then
          METADATA_PORT=$(cat /proc/cmdline | tr ' ' '\n' | grep '^metadata_port=' | cut -d'=' -f2)
          if [ -z "$METADATA_PORT" ]; then
            echo "metadata_port not found in kernel cmdline"
            echo "available=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          export METADATA_PORT
        fi
        echo "available=true" >> "$GITHUB_OUTPUT"
        echo "metadata_addr=192.168.127.1:${METADATA_PORT}" >> "$GITHUB_OUTPUT"

    - name: Phone home and configure testbox
      if: steps.metadata.outputs.available == 'true' && inputs.testbox_id != ''
      shell: bash
      env:
        TESTBOX_ID: ${{ inputs.testbox_id }}
        API_URL_OVERRIDE: ${{ inputs.api_url }}
      run: |
        METADATA_ADDR="${{ steps.metadata.outputs.metadata_addr }}"
        STATE=/tmp/.testbox
        mkdir -p "$STATE"
        chmod 700 "$STATE"

        INSTALLATION_MODEL_ID=$(curl -s --connect-timeout 2 --max-time 5 "http://${METADATA_ADDR}/installationModelID")
        if [ -n "$API_URL_OVERRIDE" ]; then
          API_URL="$API_URL_OVERRIDE"
        else
          API_URL=$(curl -s --connect-timeout 2 --max-time 5 "http://${METADATA_ADDR}/backendURL")
        fi

        # Piggyback on the VM's stickyDiskToken for phone-home authentication.
        # This is a Sanctum token that proves the caller is a real Blacksmith VM
        # belonging to the claimed installation — it's only accessible from inside
        # the VM via the metadata service and is not publicly visible.
        AUTH_TOKEN=$(curl -s --connect-timeout 2 --max-time 5 "http://${METADATA_ADDR}/stickyDiskToken")

        if [ -z "$API_URL" ] || [ -z "$INSTALLATION_MODEL_ID" ] || [ -z "$AUTH_TOKEN" ]; then
          echo "Warning: could not read required metadata (backendURL, installationModelID, stickyDiskToken)"
          exit 0
        fi

        if [ -n "$BLACKSMITH_HOSTNAME" ]; then
          RUNNER_HOST="$BLACKSMITH_HOSTNAME"
        else
          RUNNER_HOST="$BLACKSMITH_HOST_PUBLIC_IP"
        fi
        RUNNER_SSH_PORT="${BLACKSMITH_SSH_PORT:-22}"

        RESPONSE=$(curl -s -f -X POST "${API_URL}/api/testbox/phone-home" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${AUTH_TOKEN}" \
          -d "{
            \"testbox_id\": \"${TESTBOX_ID}\",
            \"installation_model_id\": ${INSTALLATION_MODEL_ID},
            \"status\": \"hydrating\",
            \"ip_address\": \"${RUNNER_HOST}\",
            \"ssh_port\": \"${RUNNER_SSH_PORT}\",
            \"working_directory\": \"${GITHUB_WORKSPACE}\",
            \"adopted_run_id\": \"${GITHUB_RUN_ID}\",
            \"metadata\": {}
          }" 2>/dev/null) || {
          echo "Warning: phone-home (hydrating) failed, continuing in degraded mode"
          RESPONSE=""
        }

        echo "$TESTBOX_ID" > "$STATE/testbox_id"
        echo "$INSTALLATION_MODEL_ID" > "$STATE/installation_model_id"
        echo "$AUTH_TOKEN" > "$STATE/auth_token"
        echo "$API_URL" > "$STATE/api_url"
        echo "$RUNNER_HOST" > "$STATE/runner_host"
        echo "$RUNNER_SSH_PORT" > "$STATE/runner_ssh_port"
        echo "$GITHUB_WORKSPACE" > "$STATE/working_directory"
        echo "$GITHUB_RUN_ID" > "$STATE/adopted_run_id"

        if [ -n "$RESPONSE" ]; then
          echo "$RESPONSE" | jq -r '.ssh_public_key // empty' > "$STATE/ssh_public_key"
          IDLE_TIMEOUT=$(echo "$RESPONSE" | jq -r '.idle_timeout // empty')
          echo "${IDLE_TIMEOUT:-10}" > "$STATE/idle_timeout"
        else
          echo "" > "$STATE/ssh_public_key"
          echo "10" > "$STATE/idle_timeout"
        fi

        echo "Testbox initialized: testbox_id=${TESTBOX_ID}"

    - name: Install SSH public key
      if: steps.metadata.outputs.available == 'true' && inputs.testbox_id != ''
      shell: bash
      run: |
        STATE=/tmp/.testbox
        SSH_PUBLIC_KEY=$(cat "$STATE/ssh_public_key" 2>/dev/null)
        if [ -n "$SSH_PUBLIC_KEY" ]; then
          mkdir -p ~/.ssh
          echo "$SSH_PUBLIC_KEY" >> ~/.ssh/authorized_keys
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/authorized_keys
          echo "SSH public key installed"
        fi

    - name: Install rsync
      if: steps.metadata.outputs.available == 'true' && inputs.testbox_id != ''
      shell: bash
      run: |
        which rsync || sudo apt-get install -y rsync
